/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import org.edisoncor.gui.button.ButtonAqua;
import org.edisoncor.gui.comboBox.ComboBoxRect;
import org.edisoncor.gui.textField.TextField;

/**
 *
 * @author danie
 */
public class RegistroPregunta extends javax.swing.JDialog {

    /**
     * Creates new form RegistroPregunta
     */
    public RegistroPregunta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRectTranslucido1 = new org.edisoncor.gui.panel.PanelRectTranslucido();
        txtId_Pregunta = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        txtDificultad = new org.edisoncor.gui.comboBox.ComboBoxRect();
        title5 = new javax.swing.JLabel();
        title6 = new javax.swing.JLabel();
        title7 = new javax.swing.JLabel();
        title8 = new javax.swing.JLabel();
        title9 = new javax.swing.JLabel();
        txtDescripcion = new org.edisoncor.gui.textField.TextField();
        txtRespuesta = new org.edisoncor.gui.textField.TextField();
        txtRegion = new org.edisoncor.gui.comboBox.ComboBoxRect();
        txtProvincia = new org.edisoncor.gui.textField.TextField();
        txtOpcion2 = new org.edisoncor.gui.textField.TextField();
        txtOpcion3 = new org.edisoncor.gui.textField.TextField();
        txtOpcion1 = new org.edisoncor.gui.textField.TextField();
        btnExaminar = new org.edisoncor.gui.button.ButtonAqua();
        imagenPregunta = new javax.swing.JLabel();
        btnEditar = new org.edisoncor.gui.button.ButtonAqua();
        btnRegistrar = new org.edisoncor.gui.button.ButtonAqua();
        btnCerrar = new javax.swing.JButton();
        title11 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRectTranslucido1.setColorDeBorde(new java.awt.Color(255, 255, 255));
        panelRectTranslucido1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panelRectTranslucido1.setColorSecundario(new java.awt.Color(0, 153, 153));

        txtId_Pregunta.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        txtId_Pregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        title2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Descripción:");

        title3.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3.setText("Respuesta:");

        title4.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title4.setText("Imagen:");

        txtDificultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fácil", "Intermedio", "Difícil" }));

        title5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title5.setText("Dificultad:");

        title6.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title6.setText("Región:");

        title7.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title7.setText("Provincia:");

        title8.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title8.setText("Opcion 1:");

        title9.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title9.setText("Opcion 2:");

        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtRegion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Insular", "Costa", "Sierra", "Amazonía" }));

        txtOpcion2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtOpcion3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtOpcion1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnExaminar.setBackground(new java.awt.Color(0, 102, 255));
        btnExaminar.setText("Examinar");
        btnExaminar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        imagenPregunta.setBackground(new java.awt.Color(255, 255, 255));
        imagenPregunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnEditar.setBackground(new java.awt.Color(0, 102, 255));
        btnEditar.setText("Editar");
        btnEditar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N

        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        title11.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        title11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title11.setText("Opcion 3:");

        titulo.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("REGISTRO DE PREGUNTA");

        javax.swing.GroupLayout panelRectTranslucido1Layout = new javax.swing.GroupLayout(panelRectTranslucido1);
        panelRectTranslucido1.setLayout(panelRectTranslucido1Layout);
        panelRectTranslucido1Layout.setHorizontalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(title3)
                            .addComponent(title8)
                            .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(txtOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(69, 69, 69)
                                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(title5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(title6)
                                    .addComponent(title7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtId_Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRectTranslucido1Layout.createSequentialGroup()
                                        .addComponent(txtOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                        .addComponent(title4)))
                                .addGap(29, 29, 29)))
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(imagenPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(title11)
                    .addContainerGap(754, Short.MAX_VALUE)))
            .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(459, Short.MAX_VALUE)))
        );
        panelRectTranslucido1Layout.setVerticalGroup(
            panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtId_Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(title9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                                .addComponent(title4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(imagenPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRectTranslucido1Layout.createSequentialGroup()
                    .addContainerGap(431, Short.MAX_VALUE)
                    .addComponent(title11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(106, 106, 106)))
            .addGroup(panelRectTranslucido1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRectTranslucido1Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(496, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRectTranslucido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        
        dispose();
        
    }//GEN-LAST:event_btnCerrarActionPerformed

    public JLabel getTxtId_Pregunta() {
        return txtId_Pregunta;
    }

    public void setTxtId_Pregunta(JLabel txtId_Pregunta) {
        this.txtId_Pregunta = txtId_Pregunta;
    }    
    
    public JButton getBtnCerrar() {
        return btnCerrar;
    }

    public void setBtnCerrar(JButton btnCerrar) {
        this.btnCerrar = btnCerrar;
    }

    public ButtonAqua getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(ButtonAqua btnEditar) {
        this.btnEditar = btnEditar;
    }

    public ButtonAqua getBtnExaminar() {
        return btnExaminar;
    }

    public void setBtnExaminar(ButtonAqua btnExaminar) {
        this.btnExaminar = btnExaminar;
    }

    public ButtonAqua getBtnRegistrar() {
        return btnRegistrar;
    }

    public void setBtnRegistrar(ButtonAqua btnRegistrar) {
        this.btnRegistrar = btnRegistrar;
    }

    public JLabel getImagenPregunta() {
        return imagenPregunta;
    }

    public void setImagenPregunta(JLabel imagenPregunta) {
        this.imagenPregunta = imagenPregunta;
    }

    public TextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public void setTxtDescripcion(TextField txtDescripcion) {
        this.txtDescripcion = txtDescripcion;
    }

    public ComboBoxRect getTxtDificultad() {
        return txtDificultad;
    }

    public void setTxtDificultad(ComboBoxRect txtDificultad) {
        this.txtDificultad = txtDificultad;
    }

    public TextField getTxtOpcion1() {
        return txtOpcion1;
    }

    public void setTxtOpcion1(TextField txtOpcion1) {
        this.txtOpcion1 = txtOpcion1;
    }

    public TextField getTxtOpcion2() {
        return txtOpcion2;
    }

    public void setTxtOpcion2(TextField txtOpcion2) {
        this.txtOpcion2 = txtOpcion2;
    }

    public TextField getTxtOpcion3() {
        return txtOpcion3;
    }

    public JLabel getTitulo() {
        return titulo;
    }

    public void setTitulo(JLabel titulo) {
        this.titulo = titulo;
    }

    public void setTxtOpcion3(TextField txtOpcion3) {
        this.txtOpcion3 = txtOpcion3;
    }

    public TextField getTxtProvincia() {
        return txtProvincia;
    }

    public void setTxtProvincia(TextField txtProvincia) {
        this.txtProvincia = txtProvincia;
    }

    public ComboBoxRect getTxtRegion() {
        return txtRegion;
    }

    public void setTxtRegion(ComboBoxRect txtRegion) {
        this.txtRegion = txtRegion;
    }

    public TextField getTxtRespuesta() {
        return txtRespuesta;
    }

    public void setTxtRespuesta(TextField txtRespuesta) {
        this.txtRespuesta = txtRespuesta;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private org.edisoncor.gui.button.ButtonAqua btnEditar;
    private org.edisoncor.gui.button.ButtonAqua btnExaminar;
    private org.edisoncor.gui.button.ButtonAqua btnRegistrar;
    private javax.swing.JLabel imagenPregunta;
    private org.edisoncor.gui.panel.PanelRectTranslucido panelRectTranslucido1;
    private javax.swing.JLabel title11;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JLabel title6;
    private javax.swing.JLabel title7;
    private javax.swing.JLabel title8;
    private javax.swing.JLabel title9;
    private javax.swing.JLabel titulo;
    private org.edisoncor.gui.textField.TextField txtDescripcion;
    private org.edisoncor.gui.comboBox.ComboBoxRect txtDificultad;
    private javax.swing.JLabel txtId_Pregunta;
    private org.edisoncor.gui.textField.TextField txtOpcion1;
    private org.edisoncor.gui.textField.TextField txtOpcion2;
    private org.edisoncor.gui.textField.TextField txtOpcion3;
    private org.edisoncor.gui.textField.TextField txtProvincia;
    private org.edisoncor.gui.comboBox.ComboBoxRect txtRegion;
    private org.edisoncor.gui.textField.TextField txtRespuesta;
    // End of variables declaration//GEN-END:variables

    public Object getBtnEliminar() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
