/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author danie
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrinicipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVentana = new javax.swing.JDesktopPane();
        btnMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnQuiz = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnPerfil = new javax.swing.JMenuItem();
        btnRanking = new javax.swing.JMenuItem();
        itemAdmin = new javax.swing.JMenu();
        itemP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelVentanaLayout = new javax.swing.GroupLayout(panelVentana);
        panelVentana.setLayout(panelVentanaLayout);
        panelVentanaLayout.setHorizontalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        panelVentanaLayout.setVerticalGroup(
            panelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMenu1.setText("Aplicación");

        btnQuiz.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, 0));
        btnQuiz.setText("Quiz");
        jMenu1.add(btnQuiz);

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        btnMenuBar.add(jMenu1);

        jMenu2.setText("Usuario");

        btnPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(btnPerfil);

        btnRanking.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnRanking.setText("Ranking");
        jMenu2.add(btnRanking);

        btnMenuBar.add(jMenu2);

        itemAdmin.setText("Administración");

        itemP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemP.setText("Gestion de Preguntas");
        itemAdmin.add(itemP);

        btnMenuBar.add(itemAdmin);

        setJMenuBar(btnMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentana)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVentana)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirActionPerformed

    public JMenu getItemAdmin() {
        return itemAdmin;
    }

    public void setItemAdmin(JMenu itemAdmin) {
        this.itemAdmin = itemAdmin;
    }

    public JMenuItem getItemP() {
        return itemP;
    }

    public void setItemP(JMenuItem itemP) {
        this.itemP = itemP;
    }

    
    
    public JMenuBar getBtnMenuBar() {
        return btnMenuBar;
    }

    public void setBtnMenuBar(JMenuBar btnMenuBar) {
        this.btnMenuBar = btnMenuBar;
    }

    public JMenuItem getBtnPerfil() {
        return btnPerfil;
    }

    public void setBtnPerfil(JMenuItem btnPerfil) {
        this.btnPerfil = btnPerfil;
    }

    public JMenuItem getBtnQuiz() {
        return btnQuiz;
    }

    public void setBtnQuiz(JMenuItem btnQuiz) {
        this.btnQuiz = btnQuiz;
    }

    public JMenuItem getBtnRanking() {
        return btnRanking;
    }

    public void setBtnRanking(JMenuItem btnRanking) {
        this.btnRanking = btnRanking;
    }

    public JMenuItem getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JMenuItem btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JDesktopPane getPanelVentana() {
        return panelVentana;
    }

    public void setPanelVentana(JDesktopPane panelVentana) {
        this.panelVentana = panelVentana;
    }


    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar btnMenuBar;
    private javax.swing.JMenuItem btnPerfil;
    private javax.swing.JMenuItem btnQuiz;
    private javax.swing.JMenuItem btnRanking;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenu itemAdmin;
    private javax.swing.JMenuItem itemP;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JDesktopPane panelVentana;
    // End of variables declaration//GEN-END:variables
}
